### ISSUE TITLE
move all of the games objects out of the global namespace

### ISSUE THREAD

**Issue by Rinzii** [cpp-gamedev/DogTales#21]
Currently all of our classes are inside of the global namespace for the game which is generally considered bad practice in C++. I suggest we move everything to a game specific namespace like `namespace dt {}` or `namespace dog {}` or `namespace dogtales {}` or `namespace game {}`.

Any of the provided examples would work.

**Comment by swagween** [comment]
I vote `namespace dog {}` as it's nice and short, and `dt` could be misinterpreted as `DeltaTime`

**Comment by Rinzii** [comment]
> I vote `namespace dog {}` as it's nice and short, and `dt` could be misinterpreted as `DeltaTime`

I'm fine with this namespace. Its short and understandable.

**Comment by karnkaul** [comment]
Closed via #30
